### ISSUE TITLE
Improving function roxygen2 documentation tracking issue

### ISSUE THREAD

**Issue by harper357** [acorg/Racmacs#32]
I thought it might be useful to list out which parts of Racmacs are missing roxygen2 documentation so I (and any other volunteers) can help add it. Running `devtools::check_man()` gives the following list for missing documentation. This obviously would miss functions that have some documentation but needs to be expanded.

**Missing documentation**
- [ ] prepare_Rd: get_viewer_options.Rd:12-14: Dropping empty section \value
- [ ] checkRd: (3) file 'optimizeMap.Rd': Empty section ‘Minimum column basis’
- [ ] checkRd: (3) optimizeMap.Rd:51-67: Empty section \details
- [ ] Missing link or links in documentation object 'Racmacs.Rd':
  ‘selectOptimization’
- [ ] See section 'Cross-references' in the 'Writing R Extensions' manual.
- [ ] Argument items with no description in Rd object 'get_viewer_options':
  ‘map’
- [ ] Argument items with no description in Rd object 'make.acmap':
  ‘...’
- [ ] Undocumented arguments in documentation object 'acmap'
  ‘...’
- [ ] Documented arguments not in \usage in documentation object 'acmap':
  ‘table_name’ ‘table’ ‘ag_names’ ‘ag_date’ ‘ag_reference’ ‘sr_names’ ‘ag_shown’ ‘ag_size’ ‘ag_cols_fill’ ‘ag_cols_outline’ ‘ag_outline_width’ ‘ag_rotation’ ‘ag_aspect’ ‘ag_shape’
  ‘ag_drawing_order’ ‘sr_shown’ ‘sr_size’ ‘sr_cols_fill’ ‘sr_cols_outline’ ‘sr_outline_width’ ‘sr_rotation’ ‘sr_aspect’ ‘sr_shape’ ‘sr_drawing_order’ ‘ag_coords’ ‘sr_coords’ ‘comment’
  ‘minimum_column_basis’ ‘transformation’ ‘colbases’ ‘optimizations’
- [ ] Undocumented arguments in documentation object 'addOptimization'
  ‘warnings’
- [ ] Undocumented arguments in documentation object 'agAttributes'
  ‘value’
- [ ] Undocumented arguments in documentation object 'bootstrapMap'
  ‘.progress’
- [ ] Undocumented arguments in documentation object 'checkHemisphering'
  ‘stepsize’
- [ ] Undocumented arguments in documentation object 'colBases'
  ‘value’
- [ ] Undocumented arguments in documentation object 'convertingMaps'
  ‘...’
- [ ] Undocumented arguments in documentation object 'export_viewer'
  ‘...’
- [ ] Undocumented arguments in documentation object 'keepSingleOptimization'
  ‘optimization_number’
- [ ] Documented arguments not in \usage in documentation object 'logtiterTable':
  ‘optimization_number’
- [ ] Undocumented arguments in documentation object 'make.acmap'
  ‘fixed_column_bases’ ‘parallel_optimization’ ‘verbose’ ‘vverbose’
- [ ] Undocumented arguments in documentation object 'mapComment'
  ‘value’
- [ ] Undocumented arguments in documentation object 'mapDimensions'
  ‘map’ ‘optimization_number’
- [ ] Undocumented arguments in documentation object 'mapResiduals'
  ‘exclude_nd’ ‘optimization_number’
- [ ] Undocumented arguments in documentation object 'mapTransformation'
  ‘value’
- [ ] Undocumented arguments in documentation object 'matchStrains'
  ‘passage_matching’ ‘warnings’
- [ ] Undocumented arguments in documentation object 'mergeReport'
  ‘map1’ ‘map2’ ‘passage_matching’
- [ ] Undocumented arguments in documentation object 'moveTrappedPoints'
  ‘stepsize’ ‘vverbose’
- [ ] Undocumented arguments in documentation object 'name'
  ‘value’
- [ ] Undocumented arguments in documentation object 'optimizeMap'
  ‘fixed_column_bases’ ‘stepsize’ ‘vverbose’ ‘parallel_optimization’
- [ ] Undocumented arguments in documentation object 'plot_sr_titers'
  ‘map’ ‘serum’ ‘xlim’ ‘ylim’ ‘optimization_number’ ‘.plot’
- [ ] Undocumented arguments in documentation object 'plot_stress_per_titer'
  ‘map’ ‘exclude_nd’
- [ ] Undocumented arguments in documentation object 'plot.rac'
  ‘map’ ‘optimization_number’ ‘xlim’ ‘ylim’ ‘asp’ ‘plot_ags’ ‘plot_sr’ ‘plot_labels’ ‘grid.col’ ‘grid.margin.col’ ‘fill.alpha’ ‘outline.alpha’ ‘padding’ ‘cex’
- [ ] Undocumented arguments in documentation object 'pointStress'
  ‘warnings’ ‘exclude_nd’
- [ ] Undocumented arguments in documentation object 'procrustesMap'
  ‘comparison_optimization_number’ ‘description’
- [ ] Documented arguments not in \usage in documentation object 'procrustesMap':
  ‘target_optimization_number’
- [ ] Undocumented arguments in documentation object 'ptBaseCoords'
  ‘value’
- [ ] Undocumented arguments in documentation object 'ptCoords'
  ‘value’
- [ ] Undocumented arguments in documentation object 'ptStyles'
  ‘value’
- [ ] Undocumented arguments in documentation object 'read.titerTable'
  ‘Fnum_to_SRname’
- [ ] Undocumented arguments in documentation object 'realignMap'
  ‘translation’ ‘scaling’ ‘warnings’ ‘.alignToBaseCoords’
- [ ] Documented arguments not in \usage in documentation object 'realignMap':
  ‘alignTargetToMain’
- [ ] Undocumented arguments in documentation object 'realignOptimizations'
  ‘optimization_number’
- [ ] Undocumented arguments in documentation object 'save.coords'
  ‘antigens’ ‘sera’
- [ ] Undocumented arguments in documentation object 'save.titerTable'
  ‘antigens’ ‘sera’
- [ ] Undocumented arguments in documentation object 'selectedOptimization'
  ‘value’
- [ ] Undocumented arguments in documentation object 'setLegend'
  ‘map’ ‘legend’ ‘fill’ ‘style.bottom’ ‘style.right’
- [ ] Undocumented arguments in documentation object 'srAttributes'
  ‘value’
- [ ] Undocumented arguments in documentation object 'stressBlobs'
  ‘.progress’ ‘.check_relaxation’
- [ ] Documented arguments not in \usage in documentation object 'stressBlobs':
  ‘data’ ‘optimization_number’ ‘progress_fn’
- [ ] Undocumented arguments in documentation object 'stressTable'
  ‘optimization_number’
- [ ] Undocumented arguments in documentation object 'titerTable'
  ‘map’ ‘.name’ ‘.check’ ‘value’
- [ ] Undocumented arguments in documentation object 'titerTableLayers'
  ‘value’
- [ ] removeAntigens:
  function(map, antigens)
- [ ] removeAntigens.racchart:
  function(map, antigen_indices)
- [ ] removeAntigens:
  function(map, antigens)
- [ ] removeAntigens.racmap:
  function(map, antigen_indices)
- [ ] removeSera:
  function(map, sera)
- [ ] removeSera.racchart:
  function(map, sera_indices)
- [ ] removeSera:
  function(map, sera)
- [ ] removeSera.racmap:
  function(map, sera_indices)
- [ ] save.acmap:
  function(map, filename)
- [ ] save.acmap.racchart:
  function(map, file)
- [ ] save.acmap:
  function(map, filename)
- [ ] save.acmap.racmap:
  function(map, file)
- [ ] subsetAntigens:
  function(map, antigens)
- [ ] subsetAntigens.racmap:
  function(map, antigen_indices)
- [ ] subsetSera:
  function(map, sera)
- [ ] subsetSera.racmap:
  function(map, sera_indices)
- [ ] view:
  function(x, ...)
- [ ] view.rac:
  function(map, ..., .jsCode, .jsData, select_ags, select_sr, show_procrustes, show_stressblobs)
- [ ] as.list:
  function(x, ...)
- [ ] as.list.racchart:
  function(map)
- [ ] print:
  function(x, ...)
- [ ] print.rac:
  function(map, all)
- [ ] plot:
  function(x, ...)
- [ ] plot.rac:
  function(map, optimization_number, xlim, ylim, asp, plot_ags, plot_sr, plot_labels, grid.col, grid.margin.col, fill.alpha, outline.alpha, padding, cex)
- [ ] Undocumented code objects:
  - [ ] ‘aadjustTiters’
  - [ ] ‘ac_calcStress’
  - [ ] ‘ac_calculate_stress’
  - [ ] ‘ac_coordStress’
  - [ ] ‘ac_getTableColbases’
  - [ ] ‘ac_mapDists’
  - [ ] ‘ac_optimizationNegLogLik’
  - [ ] ‘ac_optimizationNegLogLikWrapper’
  - [ ] ‘ac_pointLogLik’
  - [ ] ‘ac_pointStress’
  - [ ] ‘ac_srNegLogLik’
  - [ ] ‘ac_tableDists’
  - [ ] ‘add_hemispheringData’
  - [ ] ‘agLikelihood’
  - [ ] ‘agStressBlobSize’
  - [ ] ‘apply_procrustes’
  - [ ] ‘bootstrapBlobs’
  - [ ] ‘calc_coord_dist’
  - [ ] ‘calc_titer_lims’
  - [ ] ‘edit_agNames’
  - [ ] ‘edit_srNames’
  - [ ] ‘grid_search’
  - [ ] ‘list_property_function_bindings’
  - [ ] ‘logtiter_to_titer’
  - [ ] ‘make.acmap.cpp’
  - [ ] ‘mapLikelihood’
  - [ ] ‘mapLims’
  - [ ] ‘mapPlotLims’
  - [ ] ‘mapPoints’
  - [ ] ‘optimizationProperties.racmap’
  - [ ] ‘plot_agMeanResiduals’
  - [ ] ‘plot_agStressPerTiter’
  - [ ] ‘plot_srMeanResiduals’
  - [ ] ‘plot_srStressPerTiter’
  - [ ] ‘plotly_agMeanResiduals’
  - [ ] ‘plotly_agStressPerTiter’
  - [ ] ‘plotly_srStressPerTiter’
  - [ ] ‘RacPlotter’
  - [ ] ‘RacPlotterOutput’
  - [ ] ‘RacTable’
  - [ ] ‘RacTableOutput’
  - [ ] ‘RacViewer’
  - [ ] ‘RacViewerOutput’
  - [ ] ‘RacViewerProxy’
  - [ ] ‘read.acmap.cpp’
  - [ ] ‘relaxMapMLE’
  - [ ] ‘renderRacPlotter’
  - [ ] ‘renderRacTable’
  - [ ] ‘renderRacViewer’
  - [ ] ‘srLikelihood’
  - [ ] ‘srMeanResiduals’
  - [ ] ‘srStressBlobSize’
  - [ ] ‘stressBlobGeometries’
  - [ ] ‘titer_to_logtiter’
  - [ ] ‘titer_types’
  - [ ] ‘titerTypes’
  - [ ] ‘update_ferret_seraNames’
  - [ ] ‘updateStress’
  - [ ] ‘view’
